name: be-app-deploy

on:
  workflow_call:
    inputs:
      environmentType:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
      nodeVersion:
        required: true
        type: string
      webAppName:
        required: true
        type: string
      pathOfWebApp:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@v2
   
    - name: Sign in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true 

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: be-app/package-lock.json

    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
      working-directory: be-app
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.webAppName }}
        path: .

    # - name: Get publish Profile
    #   id: publish-profile
    #   uses: azure/powershell@v1
    #   with:
    #     inlineScript: |
    #       $profile = Get-AzWebAppPublishingProfile -ResourceGroupName ${{ inputs.resourceGroupName }} -Name ${{ inputs.webAppName }}
    #       $profile = $profile.Replace("`r", "").Replace("`n", "")
    #       Write-Output "::set-output name=pubprofile::$profile"
    #       Remove-Variable profile      
    #     azPSVersion: latest 

    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.webAppName }}

        # deploy web app using Azure credentials
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.webAppName }}
        # publish-profile: ${{steps.publish-profile.outputs.pubprofile}}    
        package: .

  # deploy: 
  #   runs-on: ubuntu-latest

  #   steps:
    
  #   - name: Download artifact from build job
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: ${{ inputs.webAppName }}

  #         # deploy web app using Azure credentials
  #   - name: Download artifact from build job
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: ${{ inputs.webAppName }}
  #       package: ${{ inputs.pathOfWebApp }}
  #       publish-profile: ${{ secrets.AzureAppService_PublishProfile_f6178814250d4a54ab3be7602a27d6ac }} 
